.PHONY: clean All

All:
	@echo "----------Building project:[ addressArithmetic2 - Debug ]----------"
	@cd "addressArithmetic2" && "$(MAKE)" -f  "addressArithmetic2.mk"
clean:
	@echo "----------Cleaning project:[ addressArithmetic2 - Debug ]----------"
	@cd "addressArithmetic2" && "$(MAKE)" -f  "addressArithmetic2.mk" clean
